# -*- coding: utf-8 -*-
"""blog writer copy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ji8g89xSq-5Vc-szbRbzuyqCtSXS-Sjp
"""

from crewai import Agent, Task, Crew
#from langchain_openai import ChatOpenAI
#from langchain_ollama.chat_models import ChatOllama
#from langchain_groq.chat_models import ChatGroq
from aisModels_lc import GroqChatLLM, OllamaLLM
import os
#os.environ["OPENAI_API_KEY"] = "" # enter your key here

#llm = ChatOpenAI(
#    model = "crewai-llama3",
#    base_url = "http://localhost:11434/v1")

"""the crew consists of 3 members
1) planner , role: content planner
2) writer  , role: content writer
3) editor  , role: editor

"""

llm = OllamaLLM("gemma2:2b")
#llm = ChatGroq(model="llama3-70b-8192", temperature=0.0)
style = "'www.medium.com'"
#style = "'www.aviationweek.com'"
#style = "'https://www.avmiation-week.com/'"

llm.invoke("hello")

planner = Agent(
    role="Content Planner",
    goal="Plan engaging and factually accurate content on {topic}",
    backstory="You're working on planning a blog article "
              "about the topic: {topic} in {style}."
              "You collect information that helps the "
              "audience learn something "
              "and make informed decisions. "
              "You have to prepare a detailed "
              "outline and the relevant topics and sub-topics that has to be a part of the"
              "blogpost."
              "Your work is the basis for "
              "the Content Writer to write an article on this topic.",
    llm=llm,
    allow_delegation=False,
    verbose=True
)

writer = Agent(
    role="Content Writer",
    goal="Write insightful and factually accurate "
         "opinion piece about the topic: {topic}",
    backstory="You're working on a writing "
              "a new opinion piece about the topic: {topic} in {style}. "
              "You base your writing on the work of "
              "the Content Planner, who provides an outline "
              "and relevant context about the topic. "
              "You follow the main objectives and "
              "direction of the outline, "
              "as provide by the Content Planner. "
              "You also provide objective and impartial insights "
              "and back them up with information "
              "provide by the Content Planner. "
              "You acknowledge in your opinion piece "
              "when your statements are opinions "
              "as opposed to objective statements.",
    allow_delegation=False,
    llm=llm,
    verbose=True
)

editor = Agent(
    role="Editor",
    goal="Edit a given blog post to align with "
         "the writing style of the organization {style}. ",
    backstory="You are an editor who receives a blog post "
              "from the Content Writer. "
              "Your goal is to review the blog post "
              "to ensure that it follows journalistic best practices,"
              "provides balanced viewpoints "
              "when providing opinions or assertions, "
              "and also avoids major controversial topics "
              "or opinions when possible.",
    llm=llm,
    allow_delegation=False,
    verbose=True
)

plan = Task(
    description=(
        "1. Prioritize the latest trends, key players, "
            "and noteworthy news on {topic}.\n"
        "2. Identify the target audience, considering "
            "their interests and pain points.\n"
        "3. Develop a detailed content outline including "
            "an introduction, key points, and a call to action.\n"
        "4. Include SEO keywords and relevant data or sources."
    ),
    expected_output="A comprehensive content plan document "
        "with an outline, audience analysis, "
        "SEO keywords, and resources.",
    agent=planner,
)

write = Task(
    description=(
        "1. Use the content plan to craft a compelling "
            "blog post on {topic}.\n"
        "2. Incorporate SEO keywords naturally.\n"
  "3. Sections/Subtitles are properly named "
            "in an engaging manner.\n"
        "4. Ensure the post is structured with an "
            "engaging introduction, insightful body, "
            "and a summarizing conclusion.\n"
        "5. Proofread for grammatical errors and "
            "alignment with the brand's voice.\n"
        "6. Always insert specific company names and url links"
         "when making reference to some plans, figures or data.\n"
    ),
    expected_output="A well-written blog post "
        "in markdown format, ready for publication, "
        "each section should have 2 or 3 paragraphs."
        "The length of article should be greater than 800 words",
    agent=writer,
)

edit = Task(
    description=("Proofread the given blog post for "
                 "grammatical errors and "
                 "alignment with the brand's voice."),
    expected_output="A well-written blog post in markdown format, "
                    "ready for publication, "
                    "each section should have 2 or 3 paragraphs.",
    agent=editor
)

crew = Crew(
    agents=[planner, writer, editor],
    tasks=[plan, write, edit],
    verbose=True
)

inputs = {"style": style, "topic":"Exploring the potential of AI usage"}# in Aircraft Maintenance, Quality Assurance, and Continued Airworthiness."}
result = crew.kickoff(inputs=inputs)

#!pandoc am.txt -o am.docx  # markdo

